server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

# 微信公众号对接
weixin:
  config:
    originalid: gh_e067c267e056
    token: b8b6
    app-id: wx64d5cdb0215c301a
    app-secret: d4bd79a7ab3e19d0f0337cc9650e86f6
    template_id: RbEZ2jo47dQmF4A7_Ku7RsDy1x_5by6bk1Ox6rPCl4Y

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000158632718
  merchant_private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCY96h0QJaz8I3HuuDIxxUiri9khrNxpD1i4pJV3E9YPN4RcBUBZ2Wbb1UH9wL2yGVfM6UKEplKXOmh4AMIJIwKiz6ONmlQxTfwjNr72IHfQP1dR4wVdk4iyCsu3xuzOefvUB4UDRAfv+0WIMoMNXsiqf3iCFi4QUek3NVyLXicdPbI0bTwqMFGtj96CKWZm7moTwPzHdDApjNQlwv7eUcFnNIbrRFgU9OJp7vbq8oGt9nOZe03HbF/zfVUyn5EObbiHirRKWkoIvGfZxpWZ3By81BfNVTk5QvyWZ8CzdIIUvWeViwz+4Z0YZBns4ENTNx6mYLrnUeogNbV8f1UKOdLAgMBAAECggEAOXu3/hfXij83yHrdxhWqR6IVhT1paadCukpSm5ly58HX4c2w1xo4ALVRyvB0WLDuB1ytBKAAowVPdtlryj+RsNSq6V5hLU0vvGHyWPn/tBoEHG2qotYWftOiBrco/a0hD7mX1AkkqgnB2rLvuq7OWzRuh+aDEJrXhYjHXWThEkn6sSdTjZxbkfgANQfiem9Ir2kpCsxCS3BP72PDRhiPm4/arQdODWtQtyaSJY2Nd25HakQ/PwwQk0sSab6SwwNc9U0Y9GDDFy/737ubAB68JQRsVWdhDQCw+vqI4a3F9beixoLBcStFDPYjr5g4qn2e/i94CJz4B5S47icbIDX+QQKBgQDub//DgZDbKJuTQMjwL5mTnScGAStnVzDPB4klMBJzBJ5W+SdSPLT5g1iTQnz1qcf/zgZI9gWzTdWeQIa1EhEFICkZ+cQMcN/siB0E0DgOHCvlzM5z9uG2oppWvLgMYLWWA6geDya69GCO3ToVpLHhI5TpLYmS9YRGa8lVo9swqQKBgQCkPAbS58wWsus1dtNxXgPyFXLUM1Ywc8jYwBjkZ71ApdFNo3qc9DTjECu4VamJ2AMymZg26N7zbthOjArxTYmIDBy//0CHau7VMf0CpnlER7i5mA8/L0YBPioZdDW1UdJBpS7zHlZqCYNZNlyPrbob20ETEXkxWKt6+MX5uwTs0wKBgGK2Q3CxJ0NUIHRqEcY+LpqKKSm3OjziP/a16/VVXY34j4T6SWkmcNYLppPwpsMdswsYREnYcKu2wYVuuVYlUJ6Knfl/CccMw+eswjbH7S0KRLIyhBZGU1PFJZhbMOcO8p5UjTlElIg5u+/pbq6fLHVEwdV3YMlSk5yD6yplV81hAoGAJhvDnZapta6og0xiPdEJ61dswK501mNXfGv+mqkzsdeIHJLNdbP4vaNX8br2zwRvoYMgXcVlTmkvCfLW6y0Jt6bP2QE6kPGQH6oswjussdpOk8oj545pmQo6rJNZjwxAVHkmzsUAWjSA5OeHTNOL9sDGdc09KOUhTTSCg7MQrn8CgYBmZavpHF08OQN987CUWL/qEXoPgIO5CcV5IjJV8UChgTmcqq4DLspO5h+5m+ExhJg3RmFj7AWGCEEdRIQH+YLvZvDrFiJzvTRWilgxvckebjBUYA4TcaLNrWN6IrsWgEGpYAgeVtyhonoFAur50lFboi39GhLJXh19y9O7U8BnyQ==
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg9uiAvbPtRMDQjlid7RYtFrIh/oxLuzdh+NkT6Rf1H5y55N2UlwIKJOt7L2qn4AAflYEF0Jxajcea8JNZQ7JXiO0lPcu5suGwiTxGAofJHqvb8CcXsuFI033cvmddXgKXmUpsRYAej+JEdZu7ypTmUxm1vRsMJIokgrdWB8yRCJ3fERzH0uAxM9WMQzkqkq6k4oZAPPViEvF6bbOq3X+FmPbsubz+8yk3EVpojoMw+NtDu+tPrCbmWRKn8uWQ1Cp1A2meJyQnXOJrfOE48gCafcHKnw6gdnPcGa6hgIo7He3eBiHZXQD3loO3jGycU7u33Ol1glHOJg8xxHWFnDDbQIDAQAB
  notify_url: http://ekkoliu.nat100.top/api/v1/alipay/alipay_notify_url
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml